# Generated by Django 3.1.5 on 2021-02-11 04:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=200)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.category', verbose_name='service_category')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Valoration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was last modified.', verbose_name='modified at')),
                ('price', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('duration', models.DurationField(choices=[(datetime.timedelta(days=365), 'year'), (datetime.timedelta(seconds=3600), 'hour'), (datetime.timedelta(days=1), 'day'), (datetime.timedelta(days=30), 'month'), (datetime.timedelta(days=182, seconds=43200), 'semestral'), (datetime.timedelta(days=90), 'trimestral')])),
                ('is_avaible', models.BooleanField(default=True, verbose_name='avaible')),
                ('is_contract', models.BooleanField(default=True, verbose_name='contract')),
                ('used_by_membership', models.BooleanField(default=False, verbose_name='used membership')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_prices', to='services.service')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
    ]
