# Generated by Django 3.1.5 on 2021-03-23 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210323_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoration',
            name='duration',
            field=models.DurationField(choices=[('year', datetime.timedelta(days=365)), (datetime.timedelta(seconds=3600), 'hour'), (datetime.timedelta(days=1), 'day'), (datetime.timedelta(days=30), 'month'), (datetime.timedelta(days=182, seconds=43200), 'semestral'), (datetime.timedelta(days=90), 'trimestral')]),
        ),
    ]
