# Generated by Django 3.1.7 on 2021-03-23 05:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20210323_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoration',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(days=365), 'year')]),
        ),
    ]
