# Generated by Django 3.1.5 on 2021-02-11 04:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was last modified.', verbose_name='modified at')),
                ('business_name', models.CharField(max_length=70)),
                ('dni_business', models.CharField(max_length=12, unique=True)),
                ('business_heading', models.CharField(blank=True, max_length=120, null=True)),
                ('turn', models.TextField(blank=True, max_length=500, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +9999999. Up to 15 digits allowed.', regex='\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('webpage', models.URLField(blank=True, max_length=120, null=True)),
                ('work_area', models.CharField(blank=True, max_length=130, null=True)),
                ('is_recive_mentories', models.BooleanField(default=False, verbose_name='Recive mentories')),
                ('is_digital', models.BooleanField(default=False, verbose_name='Digital')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Business',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was last modified.', verbose_name='modified at')),
                ('first_name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('second_surname', models.CharField(blank=True, max_length=20, null=True)),
                ('dni', models.CharField(max_length=12, unique=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +9999999. Up to 15 digits allowed.', regex='\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('business_heading', models.CharField(blank=True, max_length=40, null=True)),
                ('turn', models.TextField(blank=True, max_length=200, null=True)),
                ('webpage', models.URLField(blank=True, max_length=120, null=True)),
                ('work_area', models.CharField(blank=True, max_length=130, null=True)),
                ('is_recive_mentories', models.BooleanField(default=False, verbose_name='Recive mentories')),
                ('is_client', models.BooleanField(default=True, verbose_name='client')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_natural_person', models.BooleanField(default=True, verbose_name='natural person')),
                ('is_legal_represent', models.BooleanField(default=False, verbose_name='legal represent')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.business')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='represent_legal',
            field=models.ManyToManyField(blank=True, related_name='client_represent', to='clients.Client'),
        ),
    ]
