# Generated by Django 3.1.5 on 2021-02-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20210216_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_natural_person',
            field=models.BooleanField(default=False, verbose_name='natural person'),
        ),
    ]
