# Generated by Django 3.1.5 on 2021-03-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20210308_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecertb',
            name='accumulated_sales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='only_family_income',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='percentage_variation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='purpose',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='suppliers_commune',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='suppliers_province',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='suppliers_region',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='total_immigrants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='total_woman',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='total_workers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='uses_renewable_energy',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='values',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='vat_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='vision',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='waste_management_plan',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='waste_site',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
