# Generated by Django 3.2.3 on 2021-07-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20210321_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignedUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was last modified.', verbose_name='modified at')),
                ('age', models.IntegerField(max_length=200)),
                ('commune', models.CharField(max_length=400)),
                ('email', models.CharField(max_length=600)),
                ('enterprise', models.CharField(max_length=600)),
                ('gender', models.CharField(max_length=600)),
                ('name', models.CharField(max_length=600)),
                ('ocupation', models.CharField(max_length=600)),
                ('participation', models.CharField(max_length=600)),
                ('phone', models.CharField(max_length=600)),
                ('turn', models.CharField(max_length=600)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
    ]
