# Generated by Django 3.2.3 on 2021-07-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_signedup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signedup',
            name='age',
            field=models.IntegerField(),
        ),
    ]
