# Generated by Django 3.2.7 on 2021-09-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_signedup_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilecertb',
            old_name='total_immigrants',
            new_name='inmigrant_partners',
        ),
        migrations.RenameField(
            model_name='profilecertb',
            old_name='total_woman',
            new_name='marginal_partners',
        ),
        migrations.RenameField(
            model_name='profilecertb',
            old_name='vat_payment',
            new_name='marginal_workers',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='access_financing',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='branding_packaging',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='circular_economy_advice',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='community_manager',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='company_digitization',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='constructions_infrastructure_qualification',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='finance_accounting_consulting',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='impact_innovation_projects',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='international_trade_advice',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='legal_advice',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='marketing_advice',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='only_family_income',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='organizational_activities',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='percentage_variation',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='strategic_advice',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='suppliers_commune',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='suppliers_province',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='suppliers_region',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='territorial_sustainability_studies',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='uses_renewable_energy',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='values',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='waste_management_plan',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='waste_site',
        ),
        migrations.RemoveField(
            model_name='profilecertb',
            name='weaknesses',
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='benefits_financial_aid',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='carbon_footprint',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='hydrica_footprint',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='impact_activities',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='link_to_you',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='management_plan_accounts',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='mypyme_single_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='partners_etnia',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='performed_activities',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='previust_costs',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='renewable_energy',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='total_partners',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='vendors_description',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='vendors_list',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='waste_ends',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='woman_partners',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='woman_workers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='workers_diferent',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='workers_employment_law',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='workers_etnia',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='workers_inmigrant',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='workers_subsidy',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='years_payment_vat',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='profilecertb',
            name='your_values',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='accumulated_sales',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='how_help_you',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='purpose',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='socio_environmental_benefits',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='vision',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
