# Generated by Django 3.2.7 on 2021-09-20 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_profilecertb_linked_entrepreneur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilecertb',
            name='partners_etnia',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='vendors_list',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='workers_diferent',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='workers_etnia',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='workers_inmigrant',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilecertb',
            name='years_payment_vat',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ServiceRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was last modified.', verbose_name='modified at')),
                ('services_list', models.TextField(blank=True, max_length=1800, null=True)),
                ('message', models.TextField(blank=True, max_length=1800, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.business')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
    ]
