# Generated by Django 3.2.7 on 2021-09-20 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_auto_20210920_0529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequests',
            name='business',
        ),
        migrations.RemoveField(
            model_name='servicerequests',
            name='client',
        ),
        migrations.AddField(
            model_name='servicerequests',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.profilecertb'),
        ),
    ]
