# Generated by Django 3.2.7 on 2021-09-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_auto_20210921_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequests',
            name='email',
            field=models.CharField(blank=True, max_length=1800, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequests',
            name='nombre',
            field=models.CharField(blank=True, max_length=1800, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequests',
            name='phone',
            field=models.CharField(blank=True, max_length=1800, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequests',
            name='username',
            field=models.CharField(blank=True, max_length=1800, null=True),
        ),
    ]
