# Generated by Django 3.2.7 on 2021-09-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_auto_20210921_0023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequests',
            old_name='nombre',
            new_name='name',
        ),
    ]
