version: '3'

volumes:
    local_postgres_data: {}
    local_postgres_data_backups: {}
    certs: {}
    vhostd: {}
    html: {}

services:
    postgres:
        image: postgres:11
        volumes:
            - local_postgres_data:/var/lib/postgresql/data
            - local_postgres_data_backups:/backups
        ports:
            - "5430:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: api

    nginx_proxy:
        image: jwilder/nginx-proxy
        restart: always
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - certs:/etc/nginx/certs:ro
          - vhostd:/etc/nginx/vhost.d
          - html:/usr/share/nginx/html
        labels:
          - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        environment:
          - NGINX_PROXY_CONTAINER=nginx_proxy
        volumes:
            - certs:/etc/nginx/certs:rw
            - vhostd:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
            - /var/run/docker.sock:/var/run/docker.sock:ro
        depends_on:
          - nginx_proxy
    

    django:
        build: ./cowork_api
        image: cowork_django
        depends_on:
            - postgres
        volumes:
            - .:/code
        expose:
            - "80"
        environment:
            - VIRTUAL_HOST=api.creanuble.cl, www.api.creanuble.cl
            - LETSENCRYPT_HOST=api.creanuble.cl, www.api.creanuble.cl
            - LETSENCRYPT_EMAIL=api@creanuble.cl
        depends_on:
            - nginx_proxy
            - letsencrypt
            - postgres
    

    react2:
        build: ./landing_cowork_ecosystem
        image: landing_cowork_ecosystem
        expose:
            - "80"
        environment:
            - VIRTUAL_HOST=creanuble.cl, www.creanuble.cl
            - LETSENCRYPT_HOST=creanuble.cl, www.creanuble.cl
            - LETSENCRYPT_EMAIL=app@creanuble.cl
        depends_on:
            - django
            - nginx_proxy
            - letsencrypt