# Generated by Django 3.2.3 on 2021-05-26 01:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0006_auto_20210324_1649'),
        ('clients', '0007_auto_20210321_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was last modified.', verbose_name='modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('discount_import', models.IntegerField(default=0)),
                ('discount_porcent', models.IntegerField(default=0)),
                ('note_internal', models.TextField(blank=True, max_length=200, null=True)),
                ('note_client', models.TextField(blank=True, max_length=200, null=True)),
                ('date_initial', models.DateTimeField()),
                ('date_finish', models.DateTimeField(blank=True, null=True)),
                ('duration_memebership', models.DurationField(blank=True, null=True)),
                ('payment_fees', models.IntegerField(default=1)),
                ('payment_final', models.IntegerField(default=0)),
                ('payment_amount', models.IntegerField(default=0)),
                ('file_contract', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/%d/')),
                ('copy_file_contract', models.FileField(blank=True, null=True, upload_to='contracts_copy/%Y/%m/%d/')),
                ('file_cancel', models.FileField(blank=True, null=True, upload_to='cancelations/%Y/%m/%d/')),
                ('is_active', models.BooleanField(default=False)),
                ('paid_out', models.BooleanField(default=False)),
                ('is_finish', models.BooleanField(default=False)),
                ('is_finish_date', models.BooleanField(default=False)),
                ('is_cancel', models.BooleanField(default=False)),
                ('client_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_mambership', to='clients.business')),
                ('client_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_mambership', to='clients.client')),
                ('valoration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valoration_membership', to='services.valoration')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
    ]
