# Generated by Django 3.2.3 on 2021-06-07 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='duration_memebership',
        ),
        migrations.AddField(
            model_name='membership',
            name='is_renovation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='renovation_uuid',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
    ]
