# Generated by Django 3.2.3 on 2021-06-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_auto_20210607_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_enterprise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_person',
            field=models.BooleanField(default=False),
        ),
    ]
