# Generated by Django 3.2.3 on 2021-06-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_auto_20210611_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='reason_cancel',
            field=models.TextField(blank=True, max_length=650, null=True),
        ),
    ]
