# Generated by Django 3.2.3 on 2021-06-20 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0004_membership_reason_cancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was last modified.', verbose_name='modified at')),
                ('name', models.CharField(max_length=300)),
                ('bank', models.CharField(max_length=300)),
                ('number_account', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('initial_amount', models.IntegerField(default=0)),
                ('amount_money', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was last modified.', verbose_name='modified at')),
                ('type_pay', models.CharField(max_length=300)),
                ('amount', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('method_pay', models.CharField(max_length=300)),
                ('is_pay', models.BooleanField(default=True)),
                ('is_spending', models.BooleanField(default=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memberships.bankaccount')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
    ]
