# Generated by Django 3.2.3 on 2021-06-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0005_bankaccount_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='comprobant_file',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_ticket',
            field=models.BooleanField(default=False),
        ),
    ]
