# Generated by Django 3.2.3 on 2021-06-25 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20210211_0457'),
        ('memberships', '0006_auto_20210624_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.book'),
        ),
        migrations.AddField(
            model_name='payment',
            name='membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memberships.membership'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_spending',
            field=models.BooleanField(default=False),
        ),
    ]
