# Generated by Django 3.2.3 on 2021-06-26 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0007_auto_20210625_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='method_pay',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='type_pay',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_null',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='pay_for_service',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='number_account',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
