# Generated by Django 3.2.3 on 2021-06-26 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20210324_1649'),
        ('memberships', '0008_auto_20210626_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='valoration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoration_membership', to='services.valoration'),
        ),
    ]
