# Generated by Django 3.2.3 on 2021-06-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0009_alter_membership_valoration'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='amount_per_fees',
            field=models.IntegerField(default=0),
        ),
    ]
