# Generated by Django 3.1.7 on 2021-04-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_business',
            field=models.BooleanField(default=False, verbose_name='business'),
        ),
    ]
