# Generated by Django 3.2.3 on 2021-07-20 22:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('A', 'admin'), ('H', 'host')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
