# Generated by Django 3.2.3 on 2021-07-23 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20210321_2243'),
        ('memberships', '0010_membership_amount_per_fees'),
        ('users', '0004_user_type_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_user',
            field=models.CharField(blank=True, choices=[('A', 'admin'), ('H', 'host'), ('C', 'client')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was last modified.', verbose_name='modified at')),
                ('message', models.TextField(blank=True, max_length=600, null=True)),
                ('response', models.TextField(blank=True, max_length=600, null=True)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_response', models.BooleanField(default=False)),
                ('is_finish', models.BooleanField(default=False)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_business', to='clients.business')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_membership', to='memberships.membership')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_operator', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_payment', to='memberships.payment')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_client', to='clients.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
    ]
